### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by MAX1MDEV** [kalvin-eliazord/Corty_Trainer#5]
It's me again. Inject worked, but there is no esp or aimbot in the game. Are you sure everything is working?

**Comment by kalvin-eliazord** [comment]
Please read the documentation.

**Comment by MAX1MDEV** [comment]
Why do you always close the ticket without giving me the right to reply?

**Comment by kalvin-eliazord** [comment]
Because I completed your issue,
If you have another problem please open another ticket.
