### ISSUE TITLE
im noob

### ISSUE THREAD

**Issue by MAX1MDEV** [kalvin-eliazord/Corty_Trainer#6]
![image](https://github.com/kalvin-eliazord/Corty_Trainer/assets/58599802/75c6f3d3-5e2a-4d49-a4c6-23aac24c1e96)
I'm not saying it doesn't work. I must be doing something wrong.....

**Comment by kalvin-eliazord** [comment]
Are you trying to inject the DLL without the -insecure mode ?

**Comment by MAX1MDEV** [comment]
> Are you trying to inject the DLL in CS2 without the -insecure mode ?

yes, am i noob?

**Comment by MAX1MDEV** [comment]
I put insecure in the startup parameters, the read menu appears for a second and then the game crashes.

**Comment by kalvin-eliazord** [comment]
![image](https://github.com/kalvin-eliazord/Corty_Trainer/assets/61147281/16fc77be-08f3-4298-9103-f10020ff831d)

I tested the console injector and the aimbot, and they are all working fine, it may be your configuration,
Did you read the documentation?? 
- Disable your antivirus etc...

**Comment by MAX1MDEV** [comment]
> ![image](https://private-user-images.githubusercontent.com/61147281/329260760-c0311a8f-e8f0-4e93-9131-baf52c504382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjI3NzUsIm5iZiI6MTcxNTI2MjQ3NSwicGF0aCI6Ii82MTE0NzI4MS8zMjkyNjA3NjAtYzAzMTFhOGYtZThmMC00ZTkzLTkxMzEtYmFmNTJjNTA0MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEzNDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NWVmYjU1NjUxZmViZjA3M2VkZmY1M2IyZDUwMTFmMjgyZDljOTFjOTljNTYxMjM4ZTBmMTk4Y2JlODk3MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EmUpMuYdPp0eNtvx-EIWi_EeF-jnXp0qS7qQkF_cjGc)
> 
> I tested the console injector and the aimbot by building them into **release mode**, and they are all working fine, it may be your configuration, Did you read the documentation??
> 
> * Disable your antivirus etc...

of course. psst. in case you didn't know, the .vs folder contains the entire project configuration)

**Comment by MAX1MDEV** [comment]
> not_leet_yet

add me
